INSERT INTO "release_dates#region" (name,value) VALUES
	 ('europe',1),
	 ('north_america',2),
	 ('australia',3),
	 ('new_zealand',4),
	 ('japan',5),
	 ('china',6),
	 ('asia',7),
	 ('worldwide',8),
	 ('korea',9),
	 ('brazil	',10);
INSERT INTO "release_dates#category" (name,value) VALUES
	 (NULL,0),
	 ('YYYYMMMM',1),
	 ('YYYY',2),
	 ('YYYYQ1',3),
	 ('YYYYQ2',4),
	 ('YYYYQ3',5),
	 ('YYYYQ4',6),
	 ('TBD',7);
INSERT INTO "platforms#category" (name,value) VALUES
	 ('console',1),
	 ('arcade',2),
	 ('platform',3),
	 ('operating_system',4),
	 ('portable_console',5),
	 ('computer',6);
INSERT INTO "games#status" (name,value) VALUES
	 ('released',0),
	 (NULL,1),
	 ('alpha',2),
	 ('beta',3),
	 ('early_access',4),
	 ('offline',5),
	 ('cancelled',6),
	 ('rumored',7),
	 ('delisted',8);
INSERT INTO "age_rating#category" (name,value) VALUES
	 ('ESRB',1),
	 ('PEGI',2),
	 ('CERO',3),
	 ('USK',4),
	 ('GRAC',5),
	 ('CLASS_IND',6),
	 ('ACB',7);

INSERT INTO "age_rating#rating" (name,value) VALUES
	 ('Three',1),
	 ('Seven',2),
	 ('Twelve',3),
	 ('Sixteen',4),
	 ('Eighteen',5),
	 ('RP',6),
	 ('EC',7),
	 ('E',8),
	 ('E10',9),
	 ('T',10),
	 ('M',11),
	 ('AO',12),
	 ('CERO_A',13),
	 ('CERO_B',14),
	 ('CERO_C',15),
	 ('CERO_D',16),
	 ('CERO_Z',17),
	 ('USK_0',18),
	 ('USK_6',19),
	 ('USK_12',20),
	 ('USK_16',21),
	 ('USK_18',22),
	 ('GRAC_ALL',23),
	 ('GRAC_Twelve',24),
	 ('GRAC_Fifteen',25),
	 ('GRAC_Eighteen',26),
	 ('GRAC_TESTING',27),
	 ('CLASS_IND_L',28),
	 ('CLASS_IND_Ten',29),
	 ('CLASS_IND_Twelve',30),
	 ('CLASS_IND_Fourteen',31),
	 ('CLASS_IND_Sixteen',32),
	 ('CLASS_IND_Eighteen',33),
	 ('ACB_G',34),
	 ('ACB_PG',35),
	 ('ACB_M',36),
	 ('ACB_MA15',37),
	 ('ACB_R18',38),
	 ('ACB_RC',39);


INSERT INTO "companies#change_date_category" (name,value) VALUES
	 (NULL,0),
	 ('YYYYMMMM',1),
	 ('YYYY',2),
	 ('YYYYQ1',3),
	 ('YYYYQ2',4),
	 ('YYYYQ3',5),
	 ('YYYYQ4',6),
	 ('TBD',7);
INSERT INTO "companies#start_date_category" (name,value) VALUES
	 (NULL,0),
	 ('YYYYMMMM',1),
	 ('YYYY',2),
	 ('YYYYQ1',3),
	 ('YYYYQ2',4),
	 ('YYYYQ3',5),
	 ('YYYYQ4',6),
	 ('TBD',7);

INSERT INTO "country_ISO3166-1" (country_name,official_name,alpha2,alpha3,code) VALUES
	 ('Afghanistan','The Islamic Republic of Afghanistan','AF','AFG',4),
	 ('Albania','The Republic of Albania','AL','ALB',8),
	 ('Antarctica','All land and ice shelves south of the 60th parallel south','AQ','ATA',10),
	 ('Algeria','The People''s Democratic Republic of Algeria','DZ','DZA',12),
	 ('American Samoa','The Territory of American Samoa','AS','ASM',16),
	 ('Andorra','The Principality of Andorra','AD','AND',20),
	 ('Angola','The Republic of Angola','AO','AGO',24),
	 ('Antigua and Barbuda','Antigua and Barbuda','AG','ATG',28),
	 ('Azerbaijan','The Republic of Azerbaijan','AZ','AZE',31),
	 ('Argentina','The Argentine Republic','AR','ARG',32),
	 ('Australia','The Commonwealth of Australia','AU','AUS',36),
	 ('Austria','The Republic of Austria','AT','AUT',40),
	 ('Bahamas (the)','The Commonwealth of The Bahamas','BS','BHS',44),
	 ('Bahrain','The Kingdom of Bahrain','BH','BHR',48),
	 ('Bangladesh','The People''s Republic of Bangladesh','BD','BGD',50),
	 ('Armenia','The Republic of Armenia','AM','ARM',51),
	 ('Barbados','Barbados','BB','BRB',52),
	 ('Belgium','The Kingdom of Belgium','BE','BEL',56),
	 ('Bermuda','Bermuda','BM','BMU',60),
	 ('Bhutan','The Kingdom of Bhutan','BT','BTN',64),
	 ('Bolivia (Plurinational State of)','The Plurinational State of Bolivia','BO','BOL',68),
	 ('Bosnia and Herzegovina','Bosnia and Herzegovina','BA','BIH',70),
	 ('Botswana','The Republic of Botswana','BW','BWA',72),
	 ('Bouvet Island','Bouvet Island','BV','BVT',74),
	 ('Brazil','The Federative Republic of Brazil','BR','BRA',76),
	 ('Belize','Belize','BZ','BLZ',84),
	 ('British Indian Ocean Territory (the)','The British Indian Ocean Territory','IO','IOT',86),
	 ('Solomon Islands','The Solomon Islands','SB','SLB',90),
	 ('Virgin Islands (British)','The Virgin Islands','VG','VGB',92),
	 ('Brunei Darussalam','The Nation of Brunei, the Abode of Peace','BN','BRN',96),
	 ('Bulgaria','The Republic of Bulgaria','BG','BGR',100),
	 ('Myanmar','The Republic of the Union of Myanmar','MM','MMR',104),
	 ('Burundi','The Republic of Burundi','BI','BDI',108),
	 ('Belarus','The Republic of Belarus','BY','BLR',112),
	 ('Cambodia','The Kingdom of Cambodia','KH','KHM',116),
	 ('Cameroon','The Republic of Cameroon','CM','CMR',120),
	 ('Canada','Canada','CA','CAN',124),
	 ('Cabo Verde','The Republic of Cabo Verde','CV','CPV',132),
	 ('Cayman Islands (the)','The Cayman Islands','KY','CYM',136),
	 ('Central African Republic (the)','The Central African Republic','CF','CAF',140),
	 ('Sri Lanka','The Democratic Socialist Republic of Sri Lanka','LK','LKA',144),
	 ('Chad','The Republic of Chad','TD','TCD',148),
	 ('Chile','The Republic of Chile','CL','CHL',152),
	 ('China','The People''s Republic of China','CN','CHN',156),
	 ('Taiwan (Province of China)','The Republic of China','TW','TWN',158),
	 ('Christmas Island','The Territory of Christmas Island','CX','CXR',162),
	 ('Cocos (Keeling) Islands (the)','The Territory of Cocos (Keeling) Islands','CC','CCK',166),
	 ('Colombia','The Republic of Colombia','CO','COL',170),
	 ('Comoros (the)','The Union of the Comoros','KM','COM',174),
	 ('Mayotte','The Department of Mayotte','YT','MYT',175),
	 ('Congo (the)','The Republic of the Congo','CG','COG',178),
	 ('Congo (the Democratic Republic of the)','The Democratic Republic of the Congo','CD','COD',180),
	 ('Cook Islands (the)','The Cook Islands','CK','COK',184),
	 ('Costa Rica','The Republic of Costa Rica','CR','CRI',188),
	 ('Croatia','The Republic of Croatia','HR','HRV',191),
	 ('Cuba','The Republic of Cuba','CU','CUB',192),
	 ('Cyprus','The Republic of Cyprus','CY','CYP',196),
	 ('Czechia','The Czech Republic','CZ','CZE',203),
	 ('Benin','The Republic of Benin','BJ','BEN',204),
	 ('Denmark','The Kingdom of Denmark','DK','DNK',208),
	 ('Dominica','The Commonwealth of Dominica','DM','DMA',212),
	 ('Dominican Republic (the)','The Dominican Republic','DO','DOM',214),
	 ('Ecuador','The Republic of Ecuador','EC','ECU',218),
	 ('El Salvador','The Republic of El Salvador','SV','SLV',222),
	 ('Equatorial Guinea','The Republic of Equatorial Guinea','GQ','GNQ',226),
	 ('Ethiopia','The Federal Democratic Republic of Ethiopia','ET','ETH',231),
	 ('Eritrea','The State of Eritrea','ER','ERI',232),
	 ('Estonia','The Republic of Estonia','EE','EST',233),
	 ('Faroe Islands (the)','The Faroe Islands','FO','FRO',234),
	 ('Falkland Islands (the) [Malvinas] [l]','The Falkland Islands','FK','FLK',238),
	 ('South Georgia and the South Sandwich Islands','South Georgia and the South Sandwich Islands','GS','SGS',239),
	 ('Fiji','The Republic of Fiji','FJ','FJI',242),
	 ('Finland','The Republic of Finland','FI','FIN',246),
	 ('Åland Islands','Åland','AX','ALA',248),
	 ('France','The French Republic','FR','FRA',250),
	 ('French Guiana','Guyane','GF','GUF',254),
	 ('French Polynesia','French Polynesia','PF','PYF',258),
	 ('French Southern Territories (the) [n]','The French Southern and Antarctic Lands','TF','ATF',260),
	 ('Djibouti','The Republic of Djibouti','DJ','DJI',262),
	 ('Gabon','The Gabonese Republic','GA','GAB',266),
	 ('Georgia','Georgia','GE','GEO',268),
	 ('Gambia (the)','The Republic of The Gambia','GM','GMB',270),
	 ('Palestine, State of','The State of Palestine','PS','PSE',275),
	 ('Germany','The Federal Republic of Germany','DE','DEU',276),
	 ('Ghana','The Republic of Ghana','GH','GHA',288),
	 ('Gibraltar','Gibraltar','GI','GIB',292),
	 ('Kiribati','The Republic of Kiribati','KI','KIR',296),
	 ('Greece','The Hellenic Republic','GR','GRC',300),
	 ('Greenland','Kalaallit Nunaat','GL','GRL',304),
	 ('Grenada','Grenada','GD','GRD',308),
	 ('Guadeloupe','Guadeloupe','GP','GLP',312),
	 ('Guam','The Territory of Guam','GU','GUM',316),
	 ('Guatemala','The Republic of Guatemala','GT','GTM',320),
	 ('Guinea','The Republic of Guinea','GN','GIN',324),
	 ('Guyana','The Co-operative Republic of Guyana','GY','GUY',328),
	 ('Haiti','The Republic of Haiti','HT','HTI',332),
	 ('Heard Island and McDonald Islands','The Territory of Heard Island and McDonald Islands','HM','HMD',334),
	 ('Holy See (the)','The Holy See','VA','VAT',336),
	 ('Honduras','The Republic of Honduras','HN','HND',340),
	 ('Hong Kong','The Hong Kong Special Administrative Region of China[10]','HK','HKG',344),
	 ('Hungary','Hungary','HU','HUN',348),
	 ('Iceland','Iceland','IS','ISL',352),
	 ('India','The Republic of India','IN','IND',356),
	 ('Indonesia','The Republic of Indonesia','ID','IDN',360),
	 ('Iran (Islamic Republic of)','The Islamic Republic of Iran','IR','IRN',364),
	 ('Iraq','The Republic of Iraq','IQ','IRQ',368),
	 ('Ireland','Ireland','IE','IRL',372),
	 ('Israel','The State of Israel','IL','ISR',376),
	 ('Italy','The Italian Republic','IT','ITA',380),
	 ('Côte d''Ivoire','The Republic of Côte d''Ivoire','CI','CIV',384),
	 ('Jamaica','Jamaica','JM','JAM',388),
	 ('Japan','Japan','JP','JPN',392),
	 ('Kazakhstan','The Republic of Kazakhstan','KZ','KAZ',398),
	 ('Jordan','The Hashemite Kingdom of Jordan','JO','JOR',400),
	 ('Kenya','The Republic of Kenya','KE','KEN',404),
	 ('Korea (the Democratic People''s Republic of) [p]','The Democratic People''s Republic of Korea','KP','PRK',408),
	 ('Korea (the Republic of)','The Republic of Korea','KR','KOR',410),
	 ('Kuwait','The State of Kuwait','KW','KWT',414),
	 ('Kyrgyzstan','The Kyrgyz Republic','KG','KGZ',417),
	 ('Lao People''s Democratic Republic (the) [r]','The Lao People''s Democratic Republic','LA','LAO',418),
	 ('Lebanon','The Lebanese Republic','LB','LBN',422),
	 ('Lesotho','The Kingdom of Lesotho','LS','LSO',426),
	 ('Latvia','The Republic of Latvia','LV','LVA',428),
	 ('Liberia','The Republic of Liberia','LR','LBR',430),
	 ('Libya','The State of Libya','LY','LBY',434),
	 ('Liechtenstein','The Principality of Liechtenstein','LI','LIE',438),
	 ('Lithuania','The Republic of Lithuania','LT','LTU',440),
	 ('Luxembourg','The Grand Duchy of Luxembourg','LU','LUX',442),
	 ('Macao','The Macao Special Administrative Region of China[11]','MO','MAC',446),
	 ('Madagascar','The Republic of Madagascar','MG','MDG',450),
	 ('Malawi','The Republic of Malawi','MW','MWI',454),
	 ('Malaysia','Malaysia','MY','MYS',458),
	 ('Maldives','The Republic of Maldives','MV','MDV',462),
	 ('Mali','The Republic of Mali','ML','MLI',466),
	 ('Malta','The Republic of Malta','MT','MLT',470),
	 ('Martinique','Martinique','MQ','MTQ',474),
	 ('Mauritania','The Islamic Republic of Mauritania','MR','MRT',478),
	 ('Mauritius','The Republic of Mauritius','MU','MUS',480),
	 ('Mexico','The United Mexican States','MX','MEX',484),
	 ('Monaco','The Principality of Monaco','MC','MCO',492),
	 ('Mongolia','Mongolia','MN','MNG',496),
	 ('Moldova (the Republic of)','The Republic of Moldova','MD','MDA',498),
	 ('Montenegro','Montenegro','ME','MNE',499),
	 ('Montserrat','Montserrat','MS','MSR',500),
	 ('Morocco','The Kingdom of Morocco','MA','MAR',504),
	 ('Mozambique','The Republic of Mozambique','MZ','MOZ',508),
	 ('Oman','The Sultanate of Oman','OM','OMN',512),
	 ('Namibia','The Republic of Namibia','NA','NAM',516),
	 ('Nauru','The Republic of Nauru','NR','NRU',520),
	 ('Nepal','The Federal Democratic Republic of Nepal','NP','NPL',524),
	 ('Netherlands, Kingdom of the','The Kingdom of the Netherlands','NL','NLD',528),
	 ('Curaçao','The Country of Curaçao','CW','CUW',531),
	 ('Aruba','Aruba','AW','ABW',533),
	 ('Sint Maarten (Dutch part)','Sint Maarten','SX','SXM',534),
	 ('Bonaire','Bonaire, Sint Eustatius and Saba','BQ','BES',535),
	 ('New Caledonia','New Caledonia','NC','NCL',540),
	 ('Vanuatu','The Republic of Vanuatu','VU','VUT',548),
	 ('New Zealand','New Zealand','NZ','NZL',554),
	 ('Nicaragua','The Republic of Nicaragua','NI','NIC',558),
	 ('Niger (the)','The Republic of the Niger','NE','NER',562),
	 ('Nigeria','The Federal Republic of Nigeria','NG','NGA',566),
	 ('Niue','Niue','NU','NIU',570),
	 ('Norfolk Island','The Territory of Norfolk Island','NF','NFK',574),
	 ('Norway','The Kingdom of Norway','NO','NOR',578),
	 ('Northern Mariana Islands (the)','The Commonwealth of the Northern Mariana Islands','MP','MNP',580),
	 ('United States Minor Outlying Islands (the)','Baker Island, Howland Island, Jarvis Island, Johnston Atoll, Kingman Reef, Midway Atoll, Navassa Island, Palmyra Atoll, and Wake Island[13]','UM','UMI',581),
	 ('Micronesia (Federated States of)','The Federated States of Micronesia','FM','FSM',583),
	 ('Marshall Islands (the)','The Republic of the Marshall Islands','MH','MHL',584),
	 ('Palau','The Republic of Palau','PW','PLW',585),
	 ('Pakistan','The Islamic Republic of Pakistan','PK','PAK',586),
	 ('Panama','The Republic of Panamá','PA','PAN',591),
	 ('Papua New Guinea','The Independent State of Papua New Guinea','PG','PNG',598),
	 ('Paraguay','The Republic of Paraguay','PY','PRY',600),
	 ('Peru','The Republic of Perú','PE','PER',604),
	 ('Philippines (the)','The Republic of the Philippines','PH','PHL',608),
	 ('Pitcairn','The Pitcairn, Henderson, Ducie and Oeno Islands','PN','PCN',612),
	 ('Poland','The Republic of Poland','PL','POL',616),
	 ('Portugal','The Portuguese Republic','PT','PRT',620),
	 ('Guinea-Bissau','The Republic of Guinea-Bissau','GW','GNB',624),
	 ('Timor-Leste','The Democratic Republic of Timor-Leste','TL','TLS',626),
	 ('Puerto Rico','The Commonwealth of Puerto Rico','PR','PRI',630),
	 ('Qatar','The State of Qatar','QA','QAT',634),
	 ('Réunion','Réunion','RE','REU',638),
	 ('Romania','Romania','RO','ROU',642),
	 ('Russian Federation (the)','The Russian Federation','RU','RUS',643),
	 ('Rwanda','The Republic of Rwanda','RW','RWA',646),
	 ('Saint Barthélemy','The Collectivity of Saint-Barthélemy','BL','BLM',652),
	 ('Saint Helena','Saint Helena, Ascension and Tristan da Cunha','SH','SHN',654),
	 ('Saint Kitts and Nevis','Saint Kitts and Nevis','KN','KNA',659),
	 ('Anguilla','Anguilla','AI','AIA',660),
	 ('Saint Lucia','Saint Lucia','LC','LCA',662),
	 ('Saint Martin (French part)','The Collectivity of Saint-Martin','MF','MAF',663),
	 ('Saint Pierre and Miquelon','The Overseas Collectivity of Saint-Pierre and Miquelon','PM','SPM',666),
	 ('Saint Vincent and the Grenadines','Saint Vincent and the Grenadines','VC','VCT',670),
	 ('San Marino','The Republic of San Marino','SM','SMR',674),
	 ('Sao Tome and Principe','The Democratic Republic of São Tomé and Príncipe','ST','STP',678),
	 ('Saudi Arabia','The Kingdom of Saudi Arabia','SA','SAU',682),
	 ('Senegal','The Republic of Senegal','SN','SEN',686),
	 ('Serbia','The Republic of Serbia','RS','SRB',688),
	 ('Seychelles','The Republic of Seychelles','SC','SYC',690),
	 ('Sierra Leone','The Republic of Sierra Leone','SL','SLE',694),
	 ('Singapore','The Republic of Singapore','SG','SGP',702),
	 ('Slovakia','The Slovak Republic','SK','SVK',703),
	 ('Viet Nam','The Socialist Republic of Viet Nam','VN','VNM',704),
	 ('Slovenia','The Republic of Slovenia','SI','SVN',705),
	 ('Somalia','The Federal Republic of Somalia','SO','SOM',706),
	 ('South Africa','The Republic of South Africa','ZA','ZAF',710),
	 ('Zimbabwe','The Republic of Zimbabwe','ZW','ZWE',716),
	 ('Spain','The Kingdom of Spain','ES','ESP',724),
	 ('South Sudan','The Republic of South Sudan','SS','SSD',728),
	 ('Sudan (the)','The Republic of the Sudan','SD','SDN',729),
	 ('Western Sahara','The Sahrawi Arab Democratic Republic','EH','ESH',732),
	 ('Suriname','The Republic of Suriname','SR','SUR',740),
	 ('Svalbard','Svalbard and Jan Mayen','SJ','SJM',744),
	 ('Eswatini','The Kingdom of Eswatini','SZ','SWZ',748),
	 ('Sweden','The Kingdom of Sweden','SE','SWE',752),
	 ('Switzerland','The Swiss Confederation','CH','CHE',756),
	 ('Syrian Arab Republic (the)','The Syrian Arab Republic','SY','SYR',760),
	 ('Tajikistan','The Republic of Tajikistan','TJ','TJK',762),
	 ('Thailand','The Kingdom of Thailand','TH','THA',764),
	 ('Togo','The Togolese Republic','TG','TGO',768),
	 ('Tokelau','Tokelau','TK','TKL',772),
	 ('Tonga','The Kingdom of Tonga','TO','TON',776),
	 ('Trinidad and Tobago','The Republic of Trinidad and Tobago','TT','TTO',780),
	 ('United Arab Emirates (the)','The United Arab Emirates','AE','ARE',784),
	 ('Tunisia','The Republic of Tunisia','TN','TUN',788),
	 ('Türkiye','The Republic of Türkiye','TR','TUR',792),
	 ('Turkmenistan','Turkmenistan','TM','TKM',795),
	 ('Turks and Caicos Islands (the)','The Turks and Caicos Islands','TC','TCA',796),
	 ('Tuvalu','Tuvalu','TV','TUV',798),
	 ('Uganda','The Republic of Uganda','UG','UGA',800),
	 ('Ukraine','Ukraine','UA','UKR',804),
	 ('North Macedonia','The Republic of North Macedonia[12]','MK','MKD',807),
	 ('Egypt','The Arab Republic of Egypt','EG','EGY',818),
	 ('United Kingdom of Great Britain and Northern Ireland (the)','The United Kingdom of Great Britain and Northern Ireland','GB','GBR',826),
	 ('Guernsey','The Bailiwick of Guernsey','GG','GGY',831),
	 ('Jersey','The Bailiwick of Jersey','JE','JEY',832),
	 ('Isle of Man','The Isle of Man','IM','IMN',833),
	 ('Tanzania, the United Republic of','The United Republic of Tanzania','TZ','TZA',834),
	 ('United States of America (the)','The United States of America','US','USA',840),
	 ('Virgin Islands (U.S.)','The Virgin Islands of the United States','VI','VIR',850),
	 ('Burkina Faso','Burkina Faso','BF','BFA',854),
	 ('Uruguay','The Oriental Republic of Uruguay','UY','URY',858),
	 ('Uzbekistan','The Republic of Uzbekistan','UZ','UZB',860),
	 ('Venezuela (Bolivarian Republic of)','The Bolivarian Republic of Venezuela','VE','VEN',862),
	 ('Wallis and Futuna','The Territory of the Wallis and Futuna Islands','WF','WLF',876),
	 ('Samoa','The Independent State of Samoa','WS','WSM',882),
	 ('Yemen','The Republic of Yemen','YE','YEM',887),
	 ('Zambia','The Republic of Zambia','ZM','ZMB',894);

INSERT INTO "games#category" (name,value) VALUES
	 (NULL,0),
	 ('dlc_addon',1),
	 ('expansion',2),
	 ('bundle',3),
	 ('standalone_expansion',4),
	 ('mod',5),
	 ('episode',6),
	 ('season',7),
	 ('remake',8),
	 ('remaster',9),
	 ('expanded_game',10),
	 ('port',11),
	 ('fork',12),
	 ('pack',13),
	 ('update',14);
