replacements_dict = {
    ' a ': ' ',
    ' the ': ' ',
    'the ': ' ',
    '!': ' ',
    '?': ' ',
    '&': ' ',
    '@': ' ',
    '-': ' ',
    '.': '',
    ',': '',
    ';': '',
    ':': '',
    '*': '',
    # "'s ": ' ',
    "'": ' ',
    '/': ' ',
    '|': ' '
}

regionEnum_dict = {
    '1': 'europe',
    '2': 'north_america',
    '3': 'australia',
    '4': 'new_zealand',
    '5': 'japan',
    '6': 'china',
    '7': 'asia',
    '8': 'worldwide',
    '9': 'korea',
    '10': 'brazil'
}

region_dict = {
    '(usa)': '2',
    '(us)': '2',
    '(u)': '2',
    '(europe)': '1',
    '(euro)': '1',
    '(eu)': '1',
    '(e)': '1',
    '(italy)': '1',
    '(ita)': '1',
    '(it)': '1',
    '(i)': '1',
    '(france)': '1',
    '(fra)': '1',
    '(fr)': '1',
    '(f)': '1',
    '(spain)': '1',
    '(esp)': '1',
    '(es)': '1',
    '(e)': '1',
    '(germany)': '1',
    '(deu)': '1',
    '(de)': '1',
    '(d)': '1',
    '(japan)': '5',
    '(jpn)': '5',
    '(jp)': '5',
    '(j)': '5',
    '(china)':'6',
    '(chn)':'6',
    '(cn)':'6',
    '(c)':'6',
    '(asia)':'7',
    '(as)':'7',
    '(korea)':'9',
    '(kor)':'9',
    '(kr)':'9',
    '(k)':'9',
    '(brazil)':'10',
    '(bra)':'10',
    '(br)':'10',
    '(b)':'10',
    '(australia)':'3',
    '(aus)':'3',
    '(au)':'3',
    '(a)':'3',
    '(new_zealand)':'4',
    '(newzealand)':'4',
    '(new zealand)':'4',
    '(nzl)':'4',
    '(nz)':'4',
    '(n)':'4',
    '(world)':'8',
    '(worldwide)':'8',
    '(w)':'8'
}

exclusion = '(pirate)', '(proto)'
