name: Secret to env

on:
  push:
    branches: [ main ]

jobs:
  secrets-in-github-actions:
    runs-on: windows-latest

    steps:
          - name: Step 1

            env: 
              CLIENT_ID: ${{ secrets.CLIENT_ID }}
              AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
     
